//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = module.exports = {};
AddArguments = module.exports.AddArguments = function(args) {
  this.left_hand_side = null;
  this.right_hand_side = null;
  if (args) {
    if (args.left_hand_side !== undefined) {
      this.left_hand_side = args.left_hand_side;
    }
    if (args.right_hand_side !== undefined) {
      this.right_hand_side = args.right_hand_side;
    }
  }
};
AddArguments.prototype = {};
AddArguments.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.left_hand_side = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.right_hand_side = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AddArguments.prototype.write = function(output) {
  output.writeStructBegin('AddArguments');
  if (this.left_hand_side !== null && this.left_hand_side !== undefined) {
    output.writeFieldBegin('left_hand_side', Thrift.Type.I32, 1);
    output.writeI32(this.left_hand_side);
    output.writeFieldEnd();
  }
  if (this.right_hand_side !== null && this.right_hand_side !== undefined) {
    output.writeFieldBegin('right_hand_side', Thrift.Type.I32, 2);
    output.writeI32(this.right_hand_side);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LoadTestArguments = module.exports.LoadTestArguments = function(args) {
  this.before = null;
  this.after = null;
  if (args) {
    if (args.before !== undefined) {
      this.before = args.before;
    }
    if (args.after !== undefined) {
      this.after = args.after;
    }
  }
};
LoadTestArguments.prototype = {};
LoadTestArguments.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.before = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.after = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LoadTestArguments.prototype.write = function(output) {
  output.writeStructBegin('LoadTestArguments');
  if (this.before !== null && this.before !== undefined) {
    output.writeFieldBegin('before', Thrift.Type.STRING, 1);
    output.writeString(this.before);
    output.writeFieldEnd();
  }
  if (this.after !== null && this.after !== undefined) {
    output.writeFieldBegin('after', Thrift.Type.STRING, 2);
    output.writeString(this.after);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

