//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./api_types');
//HELPER FUNCTIONS AND STRUCTURES

AriadneUnitTest_ariadne_add_args = function(args) {
  this.arguments = null;
  if (args) {
    if (args.arguments !== undefined) {
      this.arguments = args.arguments;
    }
  }
};
AriadneUnitTest_ariadne_add_args.prototype = {};
AriadneUnitTest_ariadne_add_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.arguments = new ttypes.AddArguments();
        this.arguments.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AriadneUnitTest_ariadne_add_args.prototype.write = function(output) {
  output.writeStructBegin('AriadneUnitTest_ariadne_add_args');
  if (this.arguments !== null && this.arguments !== undefined) {
    output.writeFieldBegin('arguments', Thrift.Type.STRUCT, 1);
    this.arguments.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AriadneUnitTest_ariadne_add_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
AriadneUnitTest_ariadne_add_result.prototype = {};
AriadneUnitTest_ariadne_add_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.AddResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AriadneUnitTest_ariadne_add_result.prototype.write = function(output) {
  output.writeStructBegin('AriadneUnitTest_ariadne_add_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AriadneUnitTest_ariadne_stop_args = function(args) {
};
AriadneUnitTest_ariadne_stop_args.prototype = {};
AriadneUnitTest_ariadne_stop_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AriadneUnitTest_ariadne_stop_args.prototype.write = function(output) {
  output.writeStructBegin('AriadneUnitTest_ariadne_stop_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AriadneUnitTest_ariadne_stop_result = function(args) {
};
AriadneUnitTest_ariadne_stop_result.prototype = {};
AriadneUnitTest_ariadne_stop_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AriadneUnitTest_ariadne_stop_result.prototype.write = function(output) {
  output.writeStructBegin('AriadneUnitTest_ariadne_stop_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AriadneUnitTestClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
AriadneUnitTestClient.prototype = {};
AriadneUnitTestClient.prototype.ariadne_add = function(arguments, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ariadne_add(arguments);
};

AriadneUnitTestClient.prototype.send_ariadne_add = function(arguments) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ariadne_add', Thrift.MessageType.CALL, this.seqid);
  var args = new AriadneUnitTest_ariadne_add_args();
  args.arguments = arguments;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AriadneUnitTestClient.prototype.recv_ariadne_add = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AriadneUnitTest_ariadne_add_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ariadne_add failed: unknown result');
};
AriadneUnitTestClient.prototype.ariadne_stop = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ariadne_stop();
};

AriadneUnitTestClient.prototype.send_ariadne_stop = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ariadne_stop', Thrift.MessageType.CALL, this.seqid);
  var args = new AriadneUnitTest_ariadne_stop_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AriadneUnitTestClient.prototype.recv_ariadne_stop = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AriadneUnitTest_ariadne_stop_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
AriadneUnitTestProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AriadneUnitTestProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AriadneUnitTestProcessor.prototype.process_ariadne_add = function(seqid, input, output) {
  var args = new AriadneUnitTest_ariadne_add_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ariadne_add(args.arguments, function (err, result) {
    var result = new AriadneUnitTest_ariadne_add_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ariadne_add", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

AriadneUnitTestProcessor.prototype.process_ariadne_stop = function(seqid, input, output) {
  var args = new AriadneUnitTest_ariadne_stop_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ariadne_stop(function (err, result) {
    var result = new AriadneUnitTest_ariadne_stop_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ariadne_stop", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

